### ISSUE TITLE
extractIncludeProto?

### ISSUE THREAD

**Issue by vorburger** [andrewparmet/buf-gradle-plugin#20]
```
$ cat build.gradle
plugins {
    id 'application'
    id 'com.parmet.buf' version '0.2.2'
}
(...)


$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:copyProtoToWorkspace'.
> Task with path 'extractIncludeProto' not found in project ':app'.
```

**Comment by vorburger** [comment]
I can work around this by adding an empty `extractIncludeProto` task to my `build.gradle`:

```
tasks.register('extractIncludeProto') {
}
```

But this probably shouldn't be needed? It's not mentioned in the README, and I've no idea what it's for.

**Comment by andrewparmet** [comment]
`extractIncludeProto` is [the extraction step](https://github.com/google/protobuf-gradle-plugin/blob/46825f926494db226c0a6b1f325c31d16a26324a/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L408) in the `protobuf-gradle-plugin`, which is assumed to have already been applied to the project. That step needs to be executed for Buf to compile the protobuf sources if any protobuf definitions refer to definitions in dependencies, e.g. `StringValue` from the protobuf "standard" library. In this project's README:

> Integration for Buf with the protobuf-gradle-plugin. 
> ...
> It works with an implicit Buf workspace that includes src/main/proto and the `include` dependencies that the protobuf-gradle-plugin extracts into "${project.buildDir}/extracted-include-protos".

Do you have a use case for Protobuf/Buf in a Gradle project in which you're not using the protobuf-gradle-plugin?

(As a side note, `extractIncludeProto` may be the wrong task dependency for Android projects, but that doesn't seem to be the issue here.)

**Comment by vorburger** [comment]
> Do you have a use case for Protobuf/Buf in a Gradle project in which you're not using the protobuf-gradle-plugin?

It was related to #24 ... I initially applied ONLY this plugin, WITHOUT `protobuf-gradle-plugin`.

Thanks a lot for your response! Closing this as intended use is clear now.
